name: yalla_kora
description: "Yalla Kora Flutter application."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  easy_localization: ^3.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_riverpod: ^3.2.1
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.3
  freezed_annotation: ^3.1.0
  get_it: ^9.2.0
  glass_kit: ^4.0.2
  intl: ^0.20.2
  json_annotation: ^4.9.0
  liquid_glass_renderer: ^0.2.0-dev.4
  phone_form_field: ^10.0.14
  pinput: ^6.0.1
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.9.1

dev_dependencies:
  build_runner: ^2.7.1

  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
    # Flutter testing framework
  # Runs code generators
  freezed: ^3.2.3
  # Generates immutable data classes
  json_serializable: ^6.11.2
  # Generates JSON serialization code (compatible with Freezed)
  retrofit_generator: ^10.2.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/SVG/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo-ExtraLight.ttf
          weight: 200
